package com.github.kamunyan.leftcrafterdead.util

enum class ModelData(val data: Int) {
    DEFAULT(1),
    MAIN_MENU_PERK(60),
    MAIN_MENU_SKILL(61),
    MAIN_MENU_SUB_GADGET(62),
    SELECT_PERK(100),
    SELECT_FIRST_SUB_GADGET_RETURN(91),
    SUB_GADGET_TYPE(92),
    SELECT_SKILL_MASTERMIND(500),
    SELECT_SKILL_ENFORCER(501),
    SELECT_SKILL_TECHNICIAN(502),
    SELECT_SKILL_GHOST(503),
    SELECT_SKILL_FUGITIVE(504),
    SKILL_BUILD_RETURN(510),
    AMMO(550)
}